spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true
    schemas: product_db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
